server:
  port: 8099
spring:
  application:
    name: Customer
  datasource:
    url: jdbc:mysql://localhost:3306/customerservice?createDatabaseIfNotExist=true
    username: root
    password: Chinnu@1997
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      
    generate-ddl: true
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/






management:
  health:
    circuitbreakers:
      enabled: true
    endpoint:
      web:
        exposure:
          include: health
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      aaa:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 10
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      aaa:
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      aaa:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
